[sel4]
kernel = { git = "https://github.com/seL4/seL4" , tag = "10.1.1" }
tools = { git = "https://github.com/seL4/seL4_tools" , branch = "10.1.x-compatible" }
util_libs  = { git = "https://github.com/seL4/util_libs" , rev = "2c4524ce84652960cda127a8b0ae6690022988ee" }

[sel4.config]
KernelRetypeFanOutLimit = 16384

[sel4.config.x86_64]
KernelArch = 'x86'
KernelX86Sel4Arch = 'x86_64'
KernelSel4Arch = 'x86_64'
# KernelIOMMU = true

[sel4.config.arm]
KernelArch = 'arm'
KernelArmSel4Arch = 'aarch32'
KernelSel4Arch = 'aarch32'
# KernelArmSMMU = true
# KernelArmHypervisorSupport = true

[sel4.config.pc99]
KernelX86Platform = 'pc99'

[sel4.config.sabre]
KernelARMPlatform = 'imx6'
KernelHaveFPU = true

[sel4.config.debug]
KernelPrinting = true
KernelDebugBuild = true

[sel4.config.release]
KernelPrinting = false
KernelDebugBuild = false

[build.pc99]

[build.sabre]
cross_compiler_prefix = "arm-linux-gnueabihf-"
