[package]
name = "cotransport"
version = "0.1.0"
authors = ["Russell Mull <russell@auxon.io>"]
edition = "2018"

[dependencies]
confignoble = { path = "../confignoble" }

[dependencies.clap]
version = "2.33.0"
default-features = false
