[package]
name = "selfe-runtime"
version = "0.1.1"
authors = ["Russell Mull <russell@auxon.io>"]
edition = "2018"
resolver = "2"

[dependencies]
selfe-sys = { path = ".." }

[build-dependencies]
selfe-config = { path = "../selfe-config" }

[features]
default = []
panic_handler = []
