[sel4]
default_platform = 'pc99'
version = '10.1.1'

[sel4.config]
KernelRetypeFanOutLimit = 256

[sel4.config.x86_64]
KernelArch = 'x86'
KernelX86Sel4Arch = 'x86_64'
KernelSel4Arch = 'x86_64'
# KernelIOMMU = true

[sel4.config.arm]
KernelArch = 'arm'
KernelArmSel4Arch = 'aarch32'
KernelSel4Arch = 'aarch32'
# KernelArmSMMU = true
# KernelArmHypervisorSupport = true

[sel4.config.pc99]
KernelX86Platform = 'pc99'

[sel4.config.sabre]
KernelARMPlatform = 'imx6'
KernelHaveFPU = true

[sel4.config.debug]
KernelPrinting = true
KernelDebugBuild = true

[sel4.config.release]
KernelPrinting = false
KernelDebugBuild = false

[build.pc99]

[build.sabre]
cross_compiler_prefix = "arm-linux-gnueabihf-"

