[package]
name = "example"
version = "0.1.0"
authors = ["Russell Mull <russell@auxon.io>"]
edition = "2018"

[dependencies]
sel4-start = { path = "../sel4-start" }
libsel4-sys-gen = { path = ".." }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
